### ISSUE TITLE
Add backwards compatibility for Upstart

### ISSUE THREAD

**Issue by conradev** [mburns/application_nodejs#1]
Add separate templates for older versions of Upstart (that do not have `setuid`/`setgid` and `env`)

**Comment by Azrael808** [comment]
Hey @conradev IDK if you ever got around to implementing this somewhere, but I've made a PR to fix the Upstart stuff for CentOS 6: https://github.com/conradev/application_nodejs/pull/14

**Comment by mburns** [comment]
I think generalizing the init system that is supported is a great idea. Given the Upstart is deprecated in large part, I don't know that we should focus on supporting those versions, outside of modern Ubuntu and CentOS.

Thanks @Azrael808 for your CentOS fix! :smile:
